# Generated by Django 4.2.7 on 2025-12-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='current_location',
            field=models.TextField(blank=True, help_text='Current delivery location', null=True),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='vehicle_type',
            field=models.CharField(blank=True, help_text='Type of vehicle (e.g., Motorcycle, Car, Bicycle)', max_length=50, null=True),
        ),
    ]
