# Generated by Django 4.2.7 on 2025-12-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_remove_deliverypartner_current_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
