# Generated by Django 6.0 on 2025-12-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_add_delivery_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypartner',
            name='address',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='age',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='bank_account_holder',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='city',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='emergency_contact1_name',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='emergency_contact1_phone',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='emergency_contact1_relation',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='emergency_contact2_name',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='emergency_contact2_phone',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='emergency_contact2_relation',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='upi_id',
        ),
    ]
